name: auto tag and release on merge pull request
on:
  push:
    branches:
      - main
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: meson setup builddir/
      - uses: sergeysova/jq-action@v2
      - name:
        id: get_project_version
        run: >-
          echo "::set-output name=version::$(
            meson introspect --projectinfo builddir |
            jq -r '.version'
          )"
      - name: Create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_project_version.outputs.version }}
          tag_prefix: ""
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true
