name: auto tag on merge pull request
on:
  push:
    branches:
      - master
      - main
jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Get Dipy version
        run: python sample/utils/version.py
        id: get_dipy_version
      - name: Create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_dipy_version.outputs.dipy_version }}
          tag_prefix: "v"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true
